version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: stockdb
    restart: unless-stopped
    env_file: .env
    ports:
      - "4001:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - stockdbv:/data/db
    networks:
      - stockdb-network

networks:
  stockdb-network:
    driver: bridge

volumes:
  stockdbv: